### ISSUE TITLE
初始化数据库失败

### ISSUE THREAD

**Issue by lan894734188** [hunterhug/AmazonBigSpiderWeb#1]
go build main.go 可以运行 
./main -s  提示无此参数

环境：4c4g centos6.9 redis mysql golang1.8
爬虫断安装正常可正常运行
手动建立beauty数据库 重新build 库内依然空白

**Comment by hunterhug** [comment]
go run main.go -s

或者

go build main.go
./main -s

都可以.

你可以贴出你的错误信息吗?

**Comment by lan894734188** [comment]
@hunterhug 
[root@Main-Server AmazonBigSpiderWeb]# go build main.go 
[root@Main-Server AmazonBigSpiderWeb]# ./main -s
2017/09/19 09:12:35 [D] [main.go:39] 加载语言: en-US 
2017/09/19 09:12:35 [D] [main.go:39] 加载语言: zh-CN 
2017/09/19 09:12:35 [D] [main.go:47] 添加i18n函数映射 
2017/09/19 09:12:35 [D] [main.go:50] 添加json格式化函数映射 
2017/09/19 09:12:35 [D] [main.go:55] 模型初始化 
2017/09/19 09:12:35 [D] [run.go:15] 数据库开跑 
flag provided but not defined: -s
Usage of ./main:
  -graceful
    	listen on open fd (after forking)
  -socketorder string
    	previous initialization order - used when more than one listener was started
  -user string
    	user
[root@Main-Server AmazonBigSpiderWeb]#

**Comment by lan894734188** [comment]
@hunterhug 
[root@Main-Server AmazonBigSpiderWeb]# go run main.go -s
2017/09/19 10:34:03 [D] [main.go:39] 加载语言: en-US 
2017/09/19 10:34:03 [D] [main.go:39] 加载语言: zh-CN 
2017/09/19 10:34:03 [D] [main.go:47] 添加i18n函数映射 
2017/09/19 10:34:03 [D] [main.go:50] 添加json格式化函数映射 
2017/09/19 10:34:03 [D] [main.go:55] 模型初始化 
2017/09/19 10:34:03 [D] [run.go:15] 数据库开跑 
flag provided but not defined: -s
Usage of /tmp/go-build422199163/command-line-arguments/_obj/exe/main:
  -graceful
    	listen on open fd (after forking)
  -socketorder string
    	previous initialization order - used when more than one listener was started
  -user string
    	user
exit status 2
[root@Main-Server AmazonBigSpiderWeb]#

**Comment by hunterhug** [comment]
你使用的golang版本和OS版本可以列一下吗?

**Comment by lan894734188** [comment]
@hunterhug 
golang 1.8
Centos 6.9

**Comment by lan894734188** [comment]
部署GoWeb时候数据库结构倒是初始化了  不知道这个为啥不行…

**Comment by hunterhug** [comment]
我也暂时找不到问题, 我已经改了代码.

你可以

go run main.go -s=1

**Comment by lan894734188** [comment]
嗯 运行后数据库结构已经导入 灰常感谢~
